image: Visual Studio 2019
configuration: Release
platform: Any CPU

dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
  - cmd: nuget restore

build:
    project: AddressResolver.sln
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
    verbosity: detailed
    
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build_script:
  - dotnet build
  - dotnet test
  - dotnet pack

deploy:
  - provider: NuGet
    api_key:
        secure: L/4PEnjSmcOp5W7UKLV9F9JnHW8+XT4ofpTddiBAefX7KTv+JeGtkQCZ+7ieKzZg
    on:
        branch: master 

nuget:
    project_feed: true

artifacts:
    - path: 'src\**\*.nupkg'