image: Visual Studio 2019
version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
  - cmd: nuget restore

build:
    project: AddressResolver.sln
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
    verbosity: detailed

build_script:
  - dotnet build
  - dotnet test
  - dotnet pack

deploy:
  - provider: NuGet
    api_key:
        secure: L/4PEnjSmcOp5W7UKLV9F9JnHW8+XT4ofpTddiBAefX7KTv+JeGtkQCZ+7ieKzZg
    on:
        branch: master 

nuget:
    project_feed: true

artifacts:
    - path: 'src\**\*.nupkg'
    - path: 'src\**\*.snupkg'